services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: cleanersco
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres-data:


